// SOURCE: PHASE6_IMPLEMENTATION_PLAN §3.4 Day 7-8 - Cluster SE 集成测试 (vs R sandwich::vcovCL)
// 教材锚点:
//   - Liang-Zeger (1986) Biometrika - 单向聚类 SE 原始论文
//   - Cameron-Gelbach-Miller (2011) REStat - 双向聚类 V_twoway = V(g1)+V(g2)-V(g1∩g2)
//   - R sandwich 3.1-3 vcovCL type="HC1" (含小样本调整 G/(G-1)*(N-1)/(N-K))
//
// 数据: plm::Grunfeld (10 firms x 20 years, 1935-1954, N=200)
//   模型: inv ~ value + capital (含截距, K=3)
//   X = [1, value, capital] (200 x 3)
//   y = inv (200)
//   cluster_firm = firm ID (0-based, G=10)
//   cluster_year = year ID (0-based, G=20)
//
// 排幻觉点:
//   E6: 小样本调整 G/(G-1)*(N-1)/(N-K), 非 1/(G-1) 或 G/(G-1)
//   I1: 双向聚类交集 (firm∩year) 每观测唯一, G12=200=N, 退化为 HC0 (但带小样本调整)
//   I2: OLS 系数必须与 R lm() 一致 (验证数据加载正确性)
//   I3: 聚类 SE 对角元素 (方差) 与 R vcovCL 一致, 容差 1e-8
//
// TDD 策略: 本测试为规约, 数值锚定 R sandwich 3.1-3 输出 (digits=17 全精度)
//   baseline 来源: tests/fixtures/econometrics/grunfeld_cluster_baseline.json
//   数据来源: tests/fixtures/econometrics/grunfeld_data.hpp (auto-generated)

#include <gtest/gtest.h>
#include <cmath>
#include <vector>

#include "cpphub/core/linalg_dynamic.hpp"
#include "cpphub/core/types.hpp"
#include "cpphub/econometrics/inference/cluster_vcov.hpp"

// Grunfeld 数据 (auto-generated by generate_grunfeld_baseline.R)
#include "grunfeld_data.hpp"

using namespace cpphub::v1::econometrics;
using cpphub::v1::Real;
using cpphub::v1::Size;
using cpphub::v1::Index;
using cpphub::v1::linalg::dynamic::MatrixXD;
using cpphub::v1::linalg::dynamic::VectorXD;

// =============================================================================
// R baseline (from grunfeld_cluster_baseline.json, sandwich 3.1-3 vcovCL type="HC1")
// 容差: 1e-8 (spec §3.5 M1 验收标准)
// =============================================================================
namespace r_baseline {

// OLS coefficients: (Intercept), value, capital
constexpr Real COEF[3] = {
    -42.714369436559359,
    0.11556215636055213,
    0.23067848873196961
};

// V_firm (cluster=~firm, type=HC1), 3x3 row-major
// R: vcovCL(fm, cluster=~firm, type="HC1")
constexpr Real V_FIRM[9] = {
    417.18891466933866,    0.2096189823713247,  -1.2171041644275291,
    0.20961898237132479,   0.00025262993872158217, -0.00065043385435184292,
    -1.2171041644275298,  -0.00065043385435184248, 0.0072194102296205551
};

// V_year (cluster=~year, type=HC1), 3x3 row-major
constexpr Real V_YEAR[9] = {
    105.53228846790155,   -0.017759368622362937, -0.31115908963970113,
    -0.01775936862236295,  6.2560087383496283e-05, -0.0001195325892122459,
    -0.31115908963970107, -0.00011953258921224595, 0.0014955496863857417
};

// V_twoway (cluster=~firm+year, type=HC1), 3x3 row-major
// Cameron-Gelbach-Miller 2011: V_twoway = V(firm) + V(year) - V(firm∩year)
constexpr Real V_TWOWAY[9] = {
    388.74749718705164,   0.19687194537927105,  -1.0314324991350929,
    0.19687194537927077,  0.00026880092549149418, -0.00070215239315323419,
    -1.0314324991350916, -0.00070215239315323408, 0.0063271189620239254
};

// Cluster counts
constexpr Index G_FIRM = 10;
constexpr Index G_YEAR = 20;
constexpr Index G_FIRM_YEAR = 200;  // 每观测唯一 (firm, year) 组合
constexpr Index N_OBS = 200;
constexpr Index K_COEF = 3;

// 小样本调整系数 (审计核对)
constexpr Real ADJ_FIRM = 1.1223914269599549;  // (10/9) * (199/197)
constexpr Real ADJ_YEAR = 1.0633181939620624;  // (20/19) * (199/197)

constexpr Real TOL = 1e-8;

}  // namespace r_baseline

// =============================================================================
// 辅助: 从 grunfeld_data.hpp 构造 MatrixXD/VectorXD/cluster_id
// =============================================================================
struct GrunfeldFixture {
    MatrixXD X;
    VectorXD y;
    MatrixXD XtX_inv;
    VectorXD residuals;
    VectorXD beta;
    std::vector<Index> firm_id;
    std::vector<Index> year_id;

    GrunfeldFixture()
        : X(grunfeld::N, grunfeld::K),
          y(grunfeld::N),
          XtX_inv(grunfeld::K, grunfeld::K),
          residuals(grunfeld::N),
          beta(grunfeld::K),
          firm_id(grunfeld::FIRM_ID, grunfeld::FIRM_ID + grunfeld::N),
          year_id(grunfeld::YEAR_ID, grunfeld::YEAR_ID + grunfeld::N) {

        // 填充 X (row-major data -> MatrixXD)
        for (Size i = 0; i < grunfeld::N; ++i) {
            for (Size j = 0; j < grunfeld::K; ++j) {
                X(i, j) = grunfeld::X_DATA[i * grunfeld::K + j];
            }
        }
        // 填充 y
        for (Size i = 0; i < grunfeld::N; ++i) {
            y(i) = grunfeld::Y_DATA[i];
        }

        // OLS: β = (X'X)^{-1} X'y
        const Eigen::MatrixXd XtX = X.eigen().transpose() * X.eigen();
        const Eigen::MatrixXd XtX_inv_eigen = XtX.llt().solve(Eigen::MatrixXd::Identity(
            static_cast<Eigen::Index>(grunfeld::K), static_cast<Eigen::Index>(grunfeld::K)));
        XtX_inv = MatrixXD(XtX_inv_eigen);

        const Eigen::VectorXd Xty = X.eigen().transpose() * y.eigen();
        beta = VectorXD(XtX_inv_eigen * Xty);

        // 残差 u = y - X*β
        residuals = VectorXD(y.eigen() - X.eigen() * beta.eigen());
    }
};

// =============================================================================
// 测试套件: GrunfeldClusterSEIntegrationTest
// =============================================================================
class GrunfeldClusterSEIntegrationTest : public ::testing::Test {
protected:
    GrunfeldFixture gf;
};

// -----------------------------------------------------------------------------
// TEST 1: 数据加载正确性 (N=200, K=3, G_firm=10, G_year=20)
// 排幻觉点 I4: 验证数据完整性, 避免 R/C++ 数据不一致
// -----------------------------------------------------------------------------
TEST_F(GrunfeldClusterSEIntegrationTest, DataIntegrity) {
    EXPECT_EQ(gf.X.rows(), r_baseline::N_OBS);
    EXPECT_EQ(gf.X.cols(), r_baseline::K_COEF);
    EXPECT_EQ(gf.y.size(), r_baseline::N_OBS);

    // cluster counts
    std::unordered_map<Index, Index> firm_unique, year_unique;
    for (Index id : gf.firm_id) firm_unique[id] = 1;
    for (Index id : gf.year_id) year_unique[id] = 1;
    EXPECT_EQ(firm_unique.size(), static_cast<size_t>(r_baseline::G_FIRM));
    EXPECT_EQ(year_unique.size(), static_cast<size_t>(r_baseline::G_YEAR));

    // 首行数据核对 (Grunfeld firm=1, year=1935, inv=317.6, value=3078.5, capital=2.8)
    EXPECT_NEAR(gf.X(0, 0), 1.0, 1e-12);        // intercept
    EXPECT_NEAR(gf.X(0, 1), 3078.5, 1e-8);       // value
    EXPECT_NEAR(gf.X(0, 2), 2.8, 1e-8);          // capital
    EXPECT_NEAR(gf.y(0), 317.6, 1e-8);           // inv
    EXPECT_EQ(gf.firm_id[0], 0);                  // 0-based firm
    EXPECT_EQ(gf.year_id[0], 0);                  // 0-based year (1935 - 1935)
}

// -----------------------------------------------------------------------------
// TEST 2: OLS 系数 vs R lm() baseline (容差 1e-10)
// 排幻觉点 I2: 系数一致性是后续 SE 对比的前提
// -----------------------------------------------------------------------------
TEST_F(GrunfeldClusterSEIntegrationTest, OLSCoefficients_MatchR) {
    for (Size i = 0; i < r_baseline::K_COEF; ++i) {
        EXPECT_NEAR(gf.beta(i), r_baseline::COEF[i], 1e-10)
            << "Coefficient " << i << " mismatch (C++=" << gf.beta(i)
            << ", R=" << r_baseline::COEF[i] << ")";
    }
}

// -----------------------------------------------------------------------------
// TEST 3: 单向聚类 (firm) vs R vcovCL(cluster=~firm, type="HC1")
// 排幻觉点 E6: 小样本调整 G/(G-1)*(N-1)/(N-K) = (10/9)*(199/197) ≈ 1.1224
// 容差: 1e-8 (spec §3.5)
// -----------------------------------------------------------------------------
TEST_F(GrunfeldClusterSEIntegrationTest, OneWayFirm_MatchR_vcovCL) {
    const MatrixXD V = compute_cluster_vcov(gf.X, gf.residuals, gf.XtX_inv,
                                              gf.firm_id, false, {});

    // 全矩阵对比 (9 个元素)
    for (Size i = 0; i < 3; ++i) {
        for (Size j = 0; j < 3; ++j) {
            const Real cxx = V(i, j);
            const Real rref = r_baseline::V_FIRM[i * 3 + j];
            EXPECT_NEAR(cxx, rref, r_baseline::TOL)
                << "V_firm(" << i << "," << j << ") mismatch (C++=" << cxx
                << ", R=" << rref << ")";
        }
    }
}

// -----------------------------------------------------------------------------
// TEST 4: 单向聚类 (year) vs R vcovCL(cluster=~year, type="HC1")
// 排幻觉点 E6: 小样本调整 (20/19)*(199/197) ≈ 1.0633
// -----------------------------------------------------------------------------
TEST_F(GrunfeldClusterSEIntegrationTest, OneWayYear_MatchR_vcovCL) {
    const MatrixXD V = compute_cluster_vcov(gf.X, gf.residuals, gf.XtX_inv,
                                              gf.year_id, false, {});

    for (Size i = 0; i < 3; ++i) {
        for (Size j = 0; j < 3; ++j) {
            const Real cxx = V(i, j);
            const Real rref = r_baseline::V_YEAR[i * 3 + j];
            EXPECT_NEAR(cxx, rref, r_baseline::TOL)
                << "V_year(" << i << "," << j << ") mismatch (C++=" << cxx
                << ", R=" << rref << ")";
        }
    }
}

// -----------------------------------------------------------------------------
// TEST 5: 双向聚类 (firm + year) vs R vcovCL(cluster=~firm+year, type="HC1")
// Cameron-Gelbach-Miller 2011: V_twoway = V(firm) + V(year) - V(firm∩year)
// 排幻觉点 I1: firm∩year 每观测唯一, G12=200, 退化为带小样本调整的 HC0
// -----------------------------------------------------------------------------
TEST_F(GrunfeldClusterSEIntegrationTest, TwoWayFirmYear_MatchR_vcovCL) {
    const MatrixXD V = compute_cluster_vcov(gf.X, gf.residuals, gf.XtX_inv,
                                              gf.firm_id, true, gf.year_id);

    for (Size i = 0; i < 3; ++i) {
        for (Size j = 0; j < 3; ++j) {
            const Real cxx = V(i, j);
            const Real rref = r_baseline::V_TWOWAY[i * 3 + j];
            // 双向聚类涉及三次单向聚类累加, 误差可能略大, 容差 1e-8
            EXPECT_NEAR(cxx, rref, r_baseline::TOL)
                << "V_twoway(" << i << "," << j << ") mismatch (C++=" << cxx
                << ", R=" << rref << ")";
        }
    }
}

// -----------------------------------------------------------------------------
// TEST 6: 双向聚类对角元素 (方差) vs R baseline SE
// 验证标准误 (sqrt(var)) 与 R 一致
// -----------------------------------------------------------------------------
TEST_F(GrunfeldClusterSEIntegrationTest, TwoWayStandardErrors_MatchR) {
    const MatrixXD V = compute_cluster_vcov(gf.X, gf.residuals, gf.XtX_inv,
                                              gf.firm_id, true, gf.year_id);
    // R SE: [19.716680683803034, 0.016395149450111585, 0.079543189287480331]
    const Real r_se[3] = {
        std::sqrt(r_baseline::V_TWOWAY[0]),  // sqrt(V(0,0))
        std::sqrt(r_baseline::V_TWOWAY[4]),  // sqrt(V(1,1))
        std::sqrt(r_baseline::V_TWOWAY[8])   // sqrt(V(2,2))
    };
    for (Size i = 0; i < 3; ++i) {
        const Real cxx_se = std::sqrt(V(i, i));
        EXPECT_NEAR(cxx_se, r_se[i], r_baseline::TOL)
            << "SE[" << i << "] mismatch (C++=" << cxx_se << ", R=" << r_se[i] << ")";
    }
}

// -----------------------------------------------------------------------------
// TEST 7: 小样本调整系数验证 (审计)
// adj_firm = (G_firm/(G_firm-1)) * ((N-1)/(N-K)) = (10/9) * (199/197)
// adj_year = (G_year/(G_year-1)) * ((N-1)/(N-K)) = (20/19) * (199/197)
// -----------------------------------------------------------------------------
TEST_F(GrunfeldClusterSEIntegrationTest, SmallSampleAdjustment_Correct) {
    const Real adj_firm_expected = static_cast<Real>(r_baseline::G_FIRM) /
                                    static_cast<Real>(r_baseline::G_FIRM - 1) *
                                    static_cast<Real>(r_baseline::N_OBS - 1) /
                                    static_cast<Real>(r_baseline::N_OBS - r_baseline::K_COEF);
    EXPECT_NEAR(adj_firm_expected, r_baseline::ADJ_FIRM, 1e-12);

    const Real adj_year_expected = static_cast<Real>(r_baseline::G_YEAR) /
                                    static_cast<Real>(r_baseline::G_YEAR - 1) *
                                    static_cast<Real>(r_baseline::N_OBS - 1) /
                                    static_cast<Real>(r_baseline::N_OBS - r_baseline::K_COEF);
    EXPECT_NEAR(adj_year_expected, r_baseline::ADJ_YEAR, 1e-12);
}

// -----------------------------------------------------------------------------
// TEST 8: 退化情况 - G=1 抛 invalid_argument (小样本调整分母为零)
// -----------------------------------------------------------------------------
TEST_F(GrunfeldClusterSEIntegrationTest, SingleCluster_Throws) {
    std::vector<Index> single_cluster(gf.firm_id.size(), 0);  // 全部同一聚类
    EXPECT_THROW(
        compute_cluster_vcov(gf.X, gf.residuals, gf.XtX_inv, single_cluster, false, {}),
        std::invalid_argument);
}

// -----------------------------------------------------------------------------
// TEST 9: 双向聚类 V(g1=g2) = V_oneway(g1) ( Cameron-Gelbach-Miller 公式自洽)
// 当 g1 == g2 时, V(g1)+V(g2)-V(g1∩g2) = V(g1)+V(g1)-V(g1) = V(g1)
// -----------------------------------------------------------------------------
TEST_F(GrunfeldClusterSEIntegrationTest, TwoWayG1EqualsG2_EqualsOneWay) {
    const MatrixXD V_oneway = compute_cluster_vcov(gf.X, gf.residuals, gf.XtX_inv,
                                                     gf.firm_id, false, {});
    const MatrixXD V_twoway_same = compute_cluster_vcov(gf.X, gf.residuals, gf.XtX_inv,
                                                          gf.firm_id, true, gf.firm_id);

    for (Size i = 0; i < 3; ++i) {
        for (Size j = 0; j < 3; ++j) {
            EXPECT_NEAR(V_oneway(i, j), V_twoway_same(i, j), 1e-10)
                << "V_oneway(" << i << "," << j << ") != V_twoway_g1=g2("
                << i << "," << j << ")";
        }
    }
}

// -----------------------------------------------------------------------------
// TEST 10: Grunfeld 残差平方和 (SSR) 验证
// 用于确认 OLS 拟合的正确性 (排幻觉: 数据 + 系数 + 残差 全链路一致)
// -----------------------------------------------------------------------------
TEST_F(GrunfeldClusterSEIntegrationTest, ResidualSumOfSquares_Positive) {
    const Real ssr = gf.residuals.eigen().squaredNorm();
    EXPECT_GT(ssr, 0.0);  // 非完美拟合
    // Grunfeld OLS (inv ~ value + capital) SSR ≈ 1748498 (R summary)
    // 不严格断言具体值, 仅验证非零非负
    EXPECT_LT(ssr, 1e10);  // 合理上界
}
